Description: >
    Project of LoiPV2 from Udacity - s3 config

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  S3BucketName:
    Description: The name of S3-bucket
    Type: String

  S3BucketKeyName:
    Description: Keypair of S3-bucket
    Type: String

  S3BucketLogsName:
    Description: Logs of S3-bucket
    Type: String

Resources:
  S3WebApp:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  S3WebAppPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3WebApp
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - 's3:GetObject'
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3WebApp', '/*']]
            Principal: '*'

  S3KeyPair:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Ref S3BucketKeyName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  S3KeyPairPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3KeyPair
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowStaticObjectDownload
            Action:
            - 's3:GetObject'
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3KeyPair', '/*']]
            Principal: '*'
          - Sid: PutObjectAccess
            Action:
            - 's3:PutObject'
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3KeyPair', '/*']]
            Principal: '*'

  S3Logs:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Ref S3BucketLogsName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  S3LogsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Logs
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowStaticObjectDownload
            Action:
            - 's3:GetObject'
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3Logs', '/*']]
            Principal: '*'
          - Sid: PutObjectAccess
            Action:
            - 's3:PutObject'
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'S3Logs', '/*']]
            Principal: '*'

Outputs:
  S3WebURI:
    Value: !Join ['', ['s3://', !Ref S3WebApp]]
    Export:
      Name: !Sub ${EnvironmentName}-S3WebURI
  
  S3KeyURI:
    Value: !Join ['', ['s3://', !Ref S3KeyPair]]
    Export:
      Name: !Sub ${EnvironmentName}-S3KeyPairURI

  S3LogsURI:
    Value: !Join ['', ['s3://', !Ref S3Logs]]
    Export:
      Name: !Sub ${EnvironmentName}-S3LogsURI

  S3Logs:
    Value: !Ref S3Logs
    Export:
      Name: !Sub ${EnvironmentName}-S3Logs